server:
  port: 8081
spring:
  application:
    name: grpc-client
grpc:
  client:
    my-service:
      address: 'static://127.0.0.1:9090'
      negotiation-type: plaintext
#      enable-keep-alive: true
#      keep-alive-without-calls: true